---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
    category: "categories"
baseurl: "http://segfault88.github.io/"
title: "segfault88 / Malcolm Lockyer"
canonifyurls: true
theme: "purehugo"
params:
    twitterName: "segfault88"
    githubName: "segfault88"
    linkedin: https://nz.linkedin.com/pub/malcolm-lockyer/b4/387/766
    description: "Go, Ruby and other stuff"
    google_analytics: "UA-66120742-1"